Add buttons and align content
HedvigInsurance/racoon pull request #1433
Opened 2023-01-24 15:13 UTC by gustaveen

## Describe your changes

## Justify why they are needed

## Jira issue(s): []

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

2023-01-24 15:13 UTC, gustaveen commented
Current dependencies on/for this PR:
* main
  * **PR #1433** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1433" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1433?utm_source=stack-comment).

2023-01-24 15:52 UTC, alebedev requested changes
Looks good visually, see questions about opening price calculator

2023-01-24 15:52 UTC, alebedev commented on apps/store/src/components/ProductCard/ProductCard.tsx
> +          <Button href={link} size="medium" variant="primary-alt">
How do you intend to open price calculator here?  Right now it simply opens product page, same as first button

When we have this working, I want to update price calculator tracking to ensure we're handling this scenario too

2023-01-24 16:04 UTC, gustaveen commented on apps/store/src/components/ProductCard/ProductCard.tsx
> +          <Button href={link} size="medium" variant="primary-alt">
Good question, me and @robinandeer talked about adding a query param to the url and check for it in PriceCalculator, and toggle the modal. Or do you have another suggestion? :) @alebedev

2023-01-24 16:10 UTC, gustaveen commented on apps/store/src/components/ProductCard/ProductCard.tsx
> +          <Button href={link} size="medium" variant="primary-alt">
And I marked it as next step so will do it in a separate PR, but I can remove the button from the PR though 👍

2023-01-25 08:43 UTC, alebedev approved these changes

2023-01-25 08:53 UTC, merged