Add next bundle analyzer to store
HedvigInsurance/racoon pull request #1514
Opened 2023-02-02 14:43 UTC by gustaveen

## Describe your changes

## Justify why they are needed

## Jira issue(s): []

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

2023-02-02 14:43 UTC, gustaveen commented
Current dependencies on/for this PR:
* main
  * **PR #1514** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1514" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1514?utm_source=stack-comment).

2023-02-02 15:27 UTC, gustaveen commented on apps/store/README.md
> +```
Wasn't sure in what Readme to put it in

2023-02-02 16:34 UTC, robinandeer requested changes
Great stuff! I bet the client bundle analysis will come in handy

Just noticed some added dependencies that must be a mistake

2023-02-03 08:02 UTC, gustaveen commented on apps/store/package.json
> +    "add": "2.0.6",
haha, I had apparently run `yarn workspace store add yarn add @next/bundle-analyzer` 🤣

2023-02-03 08:19 UTC, robinandeer approved these changes
[![cool](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/default-memes/cool.gif)](https://app.graphite.dev/macros/HedvigInsurance)

2023-02-03 08:19 UTC, alebedev approved these changes
Looks good!  Great that we aren't using webpack-bundle-analyzer directly, this setup is so much simpler

2023-02-03 08:37 UTC, merged