styles(FullScreenDialog): smooth transitions
HedvigInsurance/racoon pull request #2794
Opened 2023-07-17 11:17 UTC by guilhermespopolin

## Describe your changes

## Justify why they are needed

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

2023-07-17 11:18 UTC, guilhermespopolin commented
Current dependencies on/for this PR:
* main
  * **PR #2794** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2794" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2794?utm_source=stack-comment).

2023-07-18 08:05 UTC, guilhermespopolin commented on apps/store/src/components/PriceCalculator/PriceCalculatorAccordion.tsx
> +            />
Another solution would be update `SsnSeSection` so `ChangeSsnWarningDialog` get's rendered here instead. It would increase this file but maybe it become easier to understand. Let me know what you thing.

2023-07-18 09:36 UTC, alebedev requested changes

2023-07-18 09:38 UTC, robinandeer commented on apps/store/src/components/PriceCalculator/PriceCalculatorAccordion.tsx
> +import { ReactNode, useState } from 'react'
nit:

```suggestion
import { type ReactNode, useState } from 'react'
```

2023-07-18 09:38 UTC, robinandeer commented on apps/store/src/components/PriceCalculator/PriceCalculatorAccordion.tsx
> +      onValueChange={(sectionId) => {
Can we extract this outside the return statement? Makes it easier to read 🙂

2023-07-18 09:38 UTC, robinandeer commented on apps/store/src/components/PriceCalculator/PriceCalculatorAccordion.tsx
> +  const [showChangeSsnDialog, setShowChangeSsnDialog] = useState(false)
Do we ever need to reset this value? 🤔

2023-07-18 09:38 UTC, robinandeer commented on apps/store/src/components/PriceCalculator/SsnSeSection.tsx
> +        open={authenticated}
So we always show this if the user is authenticated? Doesn't seems like an "imperative" solution... or?

2023-07-18 13:38 UTC, robinandeer approved these changes

2023-07-18 13:38 UTC, robinandeer commented on apps/store/src/components/PriceCalculator/SsnSeSection.tsx
> +import { FormEventHandler } from 'react'
nit:

```suggestion
import { type FormEventHandler } from 'react'
```

2023-07-18 13:38 UTC, robinandeer commented on apps/store/src/components/PriceCalculator/PriceCalculatorAccordion.tsx
> +    datadogLogs.logger.info('Cleared shopSession to change SSN in price calculator')
nit: should this be a datadog RUM action?

2023-07-18 13:38 UTC, robinandeer commented on apps/store/src/components/PriceCalculator/PriceCalculatorAccordion.tsx
> +    await router.replace(url)
should we just do a hard page reload here or are we sure this works?

2023-07-18 14:13 UTC, merged