GEN-1860 - refac(ReviewsDialog): fetch reviews client side
HedvigInsurance/racoon pull request #3995
Opened 2024-02-29 12:54 UTC by guilhermespopolin

## Describe your changes

## Justify why they are needed

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

2024-02-29 12:54 UTC, guilhermespopolin commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3995?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* **#3996** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3996?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#3995** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3995?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#3994** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3994?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3995?utm_source=stack-comment).

2024-03-07 07:49 UTC, alebedev commented on apps/store/src/components/ProductReviews/ReviewsDialog.tsx
> +  const loadedWithoutComments = !isLoading && !error && reviews.length === 0
This looks a bit awkward.  What if we model state like this?
```
  state: 'loading' | 'success' | 'error'
  data: ...
  error: ...
```

Could be further refined by making sure `data` only appears on `state=success` and `error` on state=errorr`

2024-03-07 07:56 UTC, alebedev commented on apps/store/src/components/ProductReviews/ReviewsDialog.tsx
> +type State = {
General note - have you considered using jotai here?  It's not super clear to me how exactly to implement this, but things like atom dependencies and atom families count be a good way to express relations between elements of state, ex. "select scrore -> current review list now contains reviews with this score"

2024-03-07 07:57 UTC, alebedev commented on apps/store/src/pages/api/member-reviews/index.ts
> +import type { NextApiRequest, NextApiResponse } from 'next'
Since this is new API router, we can put it into `app` folder instead.  Will get caching features automatically if we need them.  But it any case it should be a default way to write new API routes

2024-03-07 07:59 UTC, alebedev commented on apps/store/src/features/memberReviews/memberReviews.ts
> +  productId: string | Array<string> | undefined,
What if we had `fetchCompanyReviewsByScore` for `productId == undefined` case?  API would be simpler

2024-03-07 08:00 UTC, alebedev commented on apps/store/src/features/memberReviews/memberReviews.ts
> +  productId: string | Array<string> | undefined,
You can also generalize other cases as `Array<String>` (which may contain 1 element)

2024-03-07 08:05 UTC, alebedev commented on apps/store/src/features/memberReviews/memberReviews.ts
> +    scores.forEach((score) => {
Can you look into simplifying this part?  Some ideas
- flatten and sort `productsReviewsByScore` before processing
- then group into score buckets and splice

2024-03-07 08:06 UTC, alebedev commented on apps/store/src/features/memberReviews/memberReviews.ts
> +    const productsReviewsByScore = await Promise.all(
They are not `ByScore` yet, right?

2024-03-07 08:07 UTC, alebedev requested changes
Good work!  Many small comments and bigger state management question inside

2024-03-12 14:37 UTC, alebedev commented on apps/store/src/features/memberReviews/memberReviews.ts
> +  productId: string | Array<string> | undefined,
It's always tricky to use api that does different things depending on some optional argument, so I'm slightly in favor of exporting two functions.  But you decide

2024-03-12 16:37 UTC, guilhermespopolin commented on apps/store/src/features/memberReviews/memberReviews.ts
> +    scores.forEach((score) => {
That would do the trick but there's still a type issue and I personally thing it's difficult to understand or way more steps. Maybe I'm over complicating it tho...

```
  const productsReviewsByScore = await Promise.all(
    productIds.map((id) => fetchProductReviewsByScore(id)),
  )
  const allReviews = productsReviewsByScore
    .filter((review): review is ReviewsByScore => review !== null)
    .flatMap((reviewByScore) => Object.values(reviewByScore).flatMap(({ reviews }) => reviews))
    .sort(sortReviewsByDate)
    .map((review) => [review.score, review] as [Score, Review])
  const _result = Object.fromEntries(allReviews) as ReviewsByScore
  Object.values(_result).forEach(({ reviews }) => reviews.splice(maxReviewsPerScore))
```

2024-03-13 12:32 UTC, guilhermespopolin commented on apps/store/src/pages/api/member-reviews/index.ts
> +import type { NextApiRequest, NextApiResponse } from 'next'
Have update it by using a route handler instead.

2024-03-13 12:33 UTC, guilhermespopolin commented on apps/store/src/features/memberReviews/memberReviews.ts
> +  } catch (error) {
You're right. That error is now being handled by the _rout handler_ by returning a HTTP 500.

2024-03-13 12:43 UTC, guilhermespopolin commented on apps/store/src/components/ProductReviews/ReviewsDialog.tsx
> +type State = {
So I've gave a try with jotai and could get some benefits from it like not having to fetch the reviews data more than once for a particular product but the end result didn't play as nice with the rest of the state abstraction and, in my opnion, it end being more complex than a simple reducer. However some improvements could be made to the reducer implementation and the component itself which I did. I think the price of refetching the data as it belongs to `ReviewsDialog` is ok given the simpler implementation and the fact that that will not be a case with the introduction of RSC.

2024-03-13 12:43 UTC, guilhermespopolin commented on apps/store/src/components/ProductReviews/ReviewsDialog.tsx
> +  const loadedWithoutComments = !isLoading && !error && reviews.length === 0
Have update it.

2024-03-13 14:40 UTC, alebedev commented on apps/store/src/features/memberReviews/memberReviews.ts
> +    scores.forEach((score) => {
Latest code in PR looks good

2024-03-13 14:43 UTC, alebedev approved these changes
Great changes, LGTM

2024-03-13 15:49 UTC, guilhermespopolin commented
### Merge activity

* **Mar 13, 11:49 AM EDT**: @guilhermespopolin started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3995).

2024-03-13 15:56 UTC, merged