Add CookieBanner component without loading OneTrust script
HedvigInsurance/racoon pull request #4150
Opened 2024-04-15 06:52 UTC by gustaveen

## Describe your changes

## Justify why they are needed

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

2024-04-15 06:53 UTC, gustaveen commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4150?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4150** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4150?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#4149** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4149?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @gustaveen and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-16 11:49 UTC, gustaveen commented on apps/store/src/components/CookieConsent/CookieConsent.tsx
> +      }
Suggested method from OneTrust docs: https://developer.onetrust.com/onetrust/docs/display-preference-center

2024-04-16 11:50 UTC, gustaveen commented on apps/store/src/components/CookieConsent/OneTrustAtom.ts
> +export const loadOneTrustAtom = atomWithStorage('loadOneTrust', false)
Not sure what the default storage is `localStorage` or `sessionStorage`?

2024-04-17 07:16 UTC, guilhermespopolin approved these changes
🚀

2024-04-17 09:34 UTC, alebedev requested changes
Good work! Left some questions in the comments. I think two critical for merging are localization and testing GTM behavior for repeated visitors

2024-04-17 09:34 UTC, alebedev commented on apps/store/.env.local.example
General comment on PR note
> Do we need to load OneTrust continuously after a user has consented? Probably to enable OneTrust to scan the site for cookies and categorise them accordingly

It would be nice to not load it for everyone, even in background mode. Does OneTrust scan our site based on usage of their SDK or is it some server-side logic?  Maybe we can rely on OneTrust being present every time someone changes/sets their consent settings - in theory we're getting enough visitors in this mode daily

2024-04-17 09:34 UTC, alebedev commented on apps/store/src/components/CookieConsent/CookieConsent.tsx
> +      }
Let's debug with Performance tab and screenshots.  If OneTrust calls the callback in sync mode, we'll be able to hide the element before the frame is rendered and user sees anything. Same logic as in React's `useLayoutEffect`

2024-04-17 09:34 UTC, alebedev commented on apps/store/src/components/CookieConsent/CookieConsent.tsx
> +        console.log('allowAll')
If you want to merge these logs, let's add more context to messages

2024-04-17 09:34 UTC, alebedev commented on apps/store/src/components/CookieConsent/CookieConsent.tsx
> +    showBanner: true,
Maybe we can make default value depend on `isAlertBoxBlosed`?

2024-04-17 09:34 UTC, alebedev commented on apps/store/src/components/CookieConsent/CookieConsent.tsx
> +                Vi använder cookies för att ge dig en bättre upplevelse, analysera hur vår webbplats
Localization?

2024-04-17 09:34 UTC, alebedev commented on apps/store/src/components/GTMLoader.tsx
> +    gtmGtag('consent', 'update', {
What happens if we're loading the site for repeated visitor?  Do we need to report current consent groups before initializing GTM?

2024-04-17 14:46 UTC, gustaveen commented on apps/store/src/components/CookieConsent/CookieConsent.tsx
> +      }
Nope, no issues of flashing content. Also checked in Performance tab and Performance insights 👍

2024-04-17 15:23 UTC, gustaveen commented on apps/store/src/components/CookieConsent/CookieConsent.tsx
> +    showBanner: true,
We could 👍

2024-04-18 07:10 UTC, gustaveen commented on apps/store/src/components/GTMLoader.tsx
> +    gtmGtag('consent', 'update', {
Hm yeah that might be the case, let's test if it is persisted

2024-04-23 08:17 UTC, alebedev approved these changes
No questions after recent discussion, looks good

2024-05-06 09:32 UTC, gustaveen commented
### Merge activity

* **May 6, 5:32 AM EDT**: @gustaveen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4150).

2024-05-06 09:40 UTC, merged