Export Dialog Title and Description
HedvigInsurance/racoon pull request #4173
Opened 2024-04-23 09:56 UTC by Youakeem

## Describe your changes

## Justify why they are needed

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

2024-04-23 09:57 UTC, Youakeem commented
* **#4173** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4173?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Youakeem and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-23 11:23 UTC, alebedev commented on apps/store/src/hooks/useLocalSessionStorage.ts
> +    window.addEventListener('storage', handleStorageChange)
This is a nice touch!

2024-04-23 11:24 UTC, alebedev commented on apps/store/src/features/carDealership/TrialExtensionForm/TrialExtensionForm.tsx
> +  const [wasMyMoneyConsentShown, setWasMyMoneyConsentShown] = useLocalSessionStorage(
We usually use jotai's `atomWithStorage` for this, is there a reason to make it different here?

2024-04-23 11:27 UTC, alebedev commented on apps/store/.env
> +RAPIO_PASSWORD_CAR_TRIAL_DEBUGGER=776cda62-c242-4de1-9acd-9e582acc2fa9
Please don't commit secrets into this repo, it's public. Not critical, since this is only staging password. But we should still treat is as compromised and rotate it

2024-04-23 11:30 UTC, alebedev commented on apps/store/.env
> +RAPIO_API_BASE_URL=https://gateway.test.hedvig.com
Discussion topic - should we commit non-secret values that are common between development and staging environment here?  Historically we stored them in Vercel's env variables only. But this means every time you add new required var, everyone else needs to update their `.env.local` or their working copy is broken.  Maybe comitting non-secrets is better in this regard

2024-04-23 11:30 UTC, alebedev commented on apps/store/src/features/carDealership/TrialExtensionForm/TrialExtensionForm.tsx
> +                      <Text size="md">Vill du gå vidare utan erbjudandet?</Text>
Localization?

2024-04-23 11:32 UTC, alebedev requested changes
Good work!  Left some comments

2024-04-23 11:41 UTC, gustaveen reviewed
Great work! 🙌 
Just translations missing and left some comments

2024-04-23 11:41 UTC, gustaveen commented on apps/store/.env
> +RAPIO_PASSWORD_CAR_TRIAL_DEBUGGER=776cda62-c242-4de1-9acd-9e582acc2fa9
Should we check in this variables? Or maybe just keep them in the example file. If you want to sync the values you could get it from Vercel

2024-04-23 11:41 UTC, gustaveen commented on apps/store/src/features/carDealership/TrialExtensionForm/TrialExtensionForm.tsx
> +              onOpenChange={(isOpen) => {
nit: maybe extract to handlerFunction instead of inline function

2024-04-23 11:41 UTC, gustaveen commented on apps/store/src/features/carDealership/TrialExtensionForm/TrialExtensionForm.tsx
> +            <Dialog.Root
Possibly extract modal to it's own component to keep the file small :)

2024-04-23 11:41 UTC, gustaveen commented on apps/store/src/hooks/useLocalSessionStorage.ts
> +export function useLocalSessionStorage<T>(
What do you think about using an atom with storage for this. since it has some of this functionality built in, like set and get?

2024-04-23 12:58 UTC, Youakeem commented on apps/store/.env
> +RAPIO_PASSWORD_CAR_TRIAL_DEBUGGER=776cda62-c242-4de1-9acd-9e582acc2fa9
Nope, added them by mistake.

2024-04-23 12:58 UTC, Youakeem commented on apps/store/src/features/carDealership/TrialExtensionForm/TrialExtensionForm.tsx
> +                      <Text size="md">Vill du gå vidare utan erbjudandet?</Text>
Yup, waiting for copy from Sonny

2024-04-23 12:59 UTC, Youakeem commented on apps/store/src/features/carDealership/TrialExtensionForm/TrialExtensionForm.tsx
> +            <Dialog.Root
Great point, was thinking about it as well!

2024-04-23 13:02 UTC, Youakeem commented on apps/store/src/hooks/useLocalSessionStorage.ts
> +export function useLocalSessionStorage<T>(
I didn't think of this as a global state, but having it in session storage practically makes it so. Will change to Jotai.

2024-04-23 14:52 UTC, Youakeem commented on apps/store/src/hooks/useLocalSessionStorage.ts
> +    window.addEventListener('storage', handleStorageChange)
Looks like it does:

```
... and subscribes to storage events for cross-tab synchronization.
```

2024-04-23 15:47 UTC, Youakeem commented on apps/store/.env
> +RAPIO_PASSWORD_CAR_TRIAL_DEBUGGER=776cda62-c242-4de1-9acd-9e582acc2fa9
Removed the changes from git history

2024-04-24 07:03 UTC, Youakeem commented on apps/store/.env
> +RAPIO_API_BASE_URL=https://gateway.test.hedvig.com
I think, in general, non-secret values that are needed for the app to function should be committed. It could be enough to have them in the `.env.local.example` file tho.

2024-04-24 07:04 UTC, Youakeem commented on apps/store/.env
> +RAPIO_API_BASE_URL=https://gateway.test.hedvig.com
However, for this PR, I revoked all the `.env` changes

2024-04-26 14:02 UTC, guilhermespopolin approved these changes
Well done. Just left some nit comments :)

2024-04-26 15:17 UTC, Youakeem commented on apps/store/src/features/carDealership/MyMoneyConsent/MyMoneyConsentConfirmation/MyMoneyConsentConfirmation.tsx
> +} & PropsWithChildren<ComponentPropsWithoutRef<typeof Dialog.Root>>
It does, will fix.

2024-04-26 15:19 UTC, Youakeem commented on apps/store/src/features/carDealership/MyMoneyConsent/MyMoneyConsentConfirmation/MyMoneyConsentConfirmation.tsx
> +  const handleClose = (isOpen: boolean) => {
Goof point!

2024-04-26 15:19 UTC, Youakeem commented on apps/store/README.md
> +When adding new keys make sure to re-download the transaltion files but running:
Thank you, sir!

2024-04-29 07:16 UTC, alebedev commented on apps/store/README.md
> +- [lokalise2 CLI](https://github.com/lokalise/lokalise-cli-2-go)
Nice, thanks for updating README!

2024-04-29 07:19 UTC, alebedev commented on apps/store/src/features/carDealership/TrialExtensionForm/TrialExtensionForm.tsx
> +            <Button onClick={handleClickSign} loading={loading}>
This element is the same with and without MyMoney.  Can be refactored with local variable to remove duplication

2024-04-29 07:22 UTC, alebedev commented on apps/store/src/features/carDealership/MyMoneyConsent/MyMoneyConsentConfirmation/MyMoneyConsentConfirmation.tsx
> +import { useTranslation } from 'next-i18next'
Dir structure question - do you think we need `MyMoneyConsent/MyMoneyConsentConfirmation` nesting?  Just putting everything under `MyMoneyConsent` should be fine

2024-04-29 07:23 UTC, alebedev commented on apps/store/src/features/carDealership/MyMoneyConsent/MyMoneyConsentConfirmation/MyMoneyConsentConfirmationAtom.ts
> +import { createJSONStorage } from 'jotai/utils'
File naming convention - if it's not a React component or class, it should start with lowercase

2024-04-29 07:23 UTC, alebedev approved these changes
Looks good!  Added some code style / structure comments, nothing critical

2024-04-29 07:33 UTC, Youakeem commented on apps/store/src/features/carDealership/MyMoneyConsent/MyMoneyConsentConfirmation/MyMoneyConsentConfirmation.tsx
> +import { useTranslation } from 'next-i18next'
I originally had `MyMoneyConsentConfirmation` under `TrialExtensionForm` so it was obvious it needed its own folder. Then, I though it belongs to the consent feature more than the form extension.

I would still like to keep it in it's own folder to colocate the styles and other files, easier to see and move around.

That said, what do you think of moving it out of `MyMoneyConsent` so well have `MyMoneyConsent`, and `MyMoneyConsentConfirmation` next to each others?

2024-04-29 07:34 UTC, Youakeem commented on apps/store/src/features/carDealership/TrialExtensionForm/TrialExtensionForm.tsx
> +            <Button onClick={handleClickSign} loading={loading}>
Sure!

2024-04-29 07:34 UTC, Youakeem commented on apps/store/README.md
> +- [lokalise2 CLI](https://github.com/lokalise/lokalise-cli-2-go)
My pleasure!

2024-04-29 08:10 UTC, alebedev commented on apps/store/src/features/carDealership/MyMoneyConsent/MyMoneyConsentConfirmation/MyMoneyConsentConfirmation.tsx
> +import { useTranslation } from 'next-i18next'
Yes, flatter structure is probably better.  I don't see anything wrong with having multiple components in the same folder either, but it's your choice

2024-04-29 08:35 UTC, Youakeem commented
### Merge activity

* **Apr 29, 4:35 AM EDT**: [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4173) rebased this pull request as part of a merge.

2024-04-29 08:40 UTC, merged