GEN-2432-feat(checkout-v2): enable CMS content for connect payment page
HedvigInsurance/racoon pull request #4547
Opened 2024-07-30 12:10 UTC by guilhermespopolin

## Describe your changes

## Justify why they are needed

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

2024-07-30 12:10 UTC, guilhermespopolin commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4547?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4547** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4547?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#4541** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4541?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#4544](https://github.com/HedvigInsurance/racoon/pull/4544) <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4544?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @guilhermespopolin and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-30 12:45 UTC, alebedev commented on apps/store/src/app/[locale]/new/checkout/[shopSessionId]/payment/trustly/fetchConnectPaymentStory.ts
> +export function fetchConnectPaymentStory(locale: RoutingLocale): Promise<ConnectPaymentStory> {
Does it need a separate module? It's tiny, we can just inline it

2024-07-30 12:47 UTC, alebedev commented on apps/store/src/app/[locale]/new/checkout/[shopSessionId]/payment/trustly/page.tsx
> +    fetchConnectPaymentStory(params.locale),
This part is cacheable and static, we should probably move it above session-specific data fetch. Otherwise it's be refetched, since `cookies()` call marks everything that follows as dynamic content

2024-07-30 12:49 UTC, alebedev commented on apps/store/src/services/storyblok/commonStoryblokComponents.ts
> +  connectPayment: ConnectPaymentBlock,
If block is only used from RSC components, we can skip registering it here. Makes client bundle smaller. For example, header and footer blocks are not registered here

2024-07-30 12:50 UTC, alebedev commented on apps/store/src/blocks/ConnectPaymentBlock.tsx
> +'use client'
Does not need to be client component

2024-07-30 12:51 UTC, alebedev requested changes
Good work! Left some comments on static vs dynamic and storyblok integration, would like to review changes again

2024-07-30 14:10 UTC, guilhermespopolin commented on apps/store/src/services/storyblok/commonStoryblokComponents.ts
> +  connectPayment: ConnectPaymentBlock,
But if we unregister it here one couldn't be able to preview it on storyblok right?!

2024-07-30 15:00 UTC, guilhermespopolin commented on apps/store/src/app/[locale]/new/checkout/[shopSessionId]/payment/trustly/page.tsx
> +    fetchConnectPaymentStory(params.locale),
How can we do that? 🤔 
Since that page is dynamic there will be no data cache for that route segment. Even it was, we're using `fetch` directly for storyblok content so how would that work?

2024-07-31 13:37 UTC, alebedev commented on apps/store/src/app/[locale]/new/checkout/[shopSessionId]/payment/trustly/page.tsx
> +    fetchConnectPaymentStory(params.locale),
Put storyblok request and other non-request-specific requests before the first call to `cookies()` and await there

2024-08-01 08:00 UTC, alebedev approved these changes
Looks good

2024-08-01 09:41 UTC, guilhermespopolin commented
### Merge activity

* **Aug 1, 5:41 AM EDT**: @guilhermespopolin started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4547).

2024-08-01 09:41 UTC, merged